sudo: true
language: python
        - "3.6"
        - "3.7"
before_install: 
        - sudo apt-get update
        - sudo apt-get install pip3
install: 
        - pip3 install -r requirements.txt
script: 
        - tox
