sudo: true
language: python
        - "3.6"
        - "3.7"
adons:
        apt:
                packages:
                        - python3-pip
install: 
        - pip3 install -r requirements.txt
script: 
        - tox
