sudo: true
dist: bionic
language: python
        - "2.7"
        - "3.6"

addons: 
        apt:
                packages:
                        - "python3"
                        - "python3-pip"
before_install: 
        - sudo apt-get update
        - sudo apt-get install python3-setuptools
install: 
        - pip3 install wheel
        - pip3 install -r requirements.txt
script: 
        - tox
